command: ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: CATALOG_NAME
    value: "lr_serverless_aws_us_catalog"
  - name: SCHEMA_NAME
    value: "solvency2demo_agentic"
  - name: WAREHOUSE_ID
    value: "ab79eced8207d29b"
  - name: DASHBOARD_ID
    value: "01f128f6dc951605aca6caa3ec26edb3"
  - name: GENIE_SPACE_ID
    value: "01f12703e70110e5b4aeec0e5f7ee98c"
